### ISSUE TITLE
API - L'en-tête de réponse content-type ne contient pas le charset UTF8

### ISSUE THREAD

**Issue by AugustinPeopleDoc** [Mak-API/website#116]
Lors de l'appel à l'API client/distribution_projects, en méthode GET, l'en-tête de réponse content-type ne contient pas le charset UTF8 et donc les caractères sont par défaut interprétés en ISO-8859-1 (conformément à la RFC HTTP 1.1), ce qui pose les problème d’interprétation des accents : ex. de réponse: "name":"Distribution paie fÃ:copyright:vrier 2018"

Par comparaison, headers de la réponse de l'API client/employees :

Connection keep-alive 
X-Robots-Tag noindex, nofollow 
X-Request-Id 603a9ffa-34ca-4881-9561-1c7f05abd8c1 
Strict-Transport-Security max-age=15552000 
X-Content-Type-Options nosniff 
Expect-CT max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" 
CF-RAY 4abf9db31e5eb783-CDG 
Content-Length 677 
Content-Type application/json; charset=utf-8 
Date Wed, 20 Feb 2019 08:31:17 GMT 
Set-Cookie __cfduid=d3738c8186f0ca4eec6c2660598f1c7b61550651476; expires=Thu, 20-Feb-20 08:31:16 GMT; path=/; domain=.people-doc.com; HttpOnly
Server cloudflare 
Via 1.1 API-Gateway 

headers de la réponse de l'API client/distribution_projects :
Transfer-Encoding chunked 
Connection keep-alive 
Vary Origin, Accept-Encoding, Accept-Language, Cookie 
Content-Language en 
Strict-Transport-Security max-age=15552000 
X-Robots-Tag noindex, nofollow 
X-Frame-Options SAMEORIGIN 
Allow GET, POST, HEAD, OPTIONS 
X-Content-Type-Options nosniff 
Expect-CT max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" 
CF-RAY 4abfa00ccc23b783-CDG 
Content-Type application/json 
Date Wed, 20 Feb 2019 08:32:53 GMT 
Set-Cookie __cfduid=d547a4b4fd64de274ef0a6917db081da71550651573; expires=Thu, 20-Feb-20 08:32:53 GMT; path=/; domain=.people-doc.com; HttpOnly
Server cloudflare 
Via 1.1 API-Gateway

Est-il possible de corriger ce point rapidement (j'ai mis en place une solution de contournement en attendant) ?

**Comment by ivanPrunier** [comment]
Bonjour @AugustinPeopleDoc, es-tu sur d'avoir créé ton Issue sur le bon repository? Ce que tu présente n'a pas l'air d'avoir de rapport avec le projet mak-api.

**Comment by AugustinPeopleDoc** [comment]
Merci, je vais le changer de repository
