### ISSUE TITLE
Mettre par défaut ROLE_USER pour "roles"

### ISSUE THREAD

**Issue by benKazmierczak** [Mak-API/website#34]
Il faudrait mettre en valeurs par défaut "ROLE_USER" pour la colonne roles de la table user_account

Pourquoi le type de roles est en text /(DC2Type:json)/ ??

**Comment by jeremNoel** [comment]
Actuellement avec la feature du service Email, le rôle par défaut est "ROLE_UNVERIFIED" btw

**Comment by Backins** [comment]
Petit bug sur ce rôle mit en getter. Aucun utilisateur n'a ce rôle

**Comment by Backins** [comment]
ROLE_UNVERIFIED à l'inscription
ROLE_USER une fois vérification faite
