### ISSUE TITLE
Inscription

### ISSUE THREAD

**Issue by benKazmierczak** [Mak-API/website#35]
Afin de permettre à un utilisateur de s'inscrire, une page inscription va devoir être réalisée.
Plusieurs champs doivent être présent et obligatoire (liste ci-dessous).

    Si je clique sur "s'inscrire" mais qu'un champ n'est pas rempli et/ou au mauvais format, une alerte doit être visible sur la page.
- Si je clique sur "s'inscrire" et que les champs sont OK : Je dois être redirigé sur une page avec le texte suivant : "Inscription réussie, merci de consulter votre boîte mail afin de confirmer votre adresse email."
- Si un utilisateur se connecte sans la confirmation de mail OK : L'utilisateur est redirigée sur une page lui expliquant le dispositif et avec un bouton lui permettant de renvoyer un mail de confirmation.

**Comment by Backins** [comment]
#44 - PR merged, close issue
