### ISSUE TITLE
Utilisation des balises <object> non supportée sur Chrome

### ISSUE THREAD

**Issue by Backins** [Mak-API/website#52]
Erreur log : 

<pre>
onloadwff.js:71 Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of null
</pre>

**Comment by Backins** [comment]
Alternative : utiliser les balises `<img />`

**Comment by typehorror** [comment]
@Backins , onloadwff est a cause de votre extension lastpass

**Comment by Backins** [comment]
Merci @debrice d'avoir pris le temps de répondre :)

Nous avions identifié le problème, mais malheureusement après avoir abandonné ce repo. Ce qui explique que nous n'ayons pas mis à jour cette issue.

Mais dans le même temps que de vous remercier, je vais prendre soin de fermer cette issue. Encore merci 💯
