### ISSUE TITLE
Hotfix - Refactoring all view with good template

### ISSUE THREAD

**Issue by mehdou92** [Mak-API/website#88]
Refactoring all template views

**Comment by mehdou92** [comment]
- Email confirmation (button color)
- Sign up (header, shadow, button)
- Sign in (shadow)
- About us (content)
- Profile (buttons, settings )
- errorPage (change content)

**Comment by Backins** [comment]
Ajout nécessité de connexion pour le MVP

**Comment by Backins** [comment]
PR et mergé
